### ISSUE TITLE
Option to reduce data volume

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#186]
As we process the real data, the parse takes a few minutes (around 2).

Once the processing is complete the compiled JSON brings VS-Code performance challenges. In particular it can take some time before it's possible to collapse JSON tree elements.

When I'm doing compile/test/inspect cycle this becomes time consuming.

One solution could be to only process a fixed number of countries (or classes).  This wouldn't work with our mock data, since we have such a small set of data. But, we could process a proportion of the data (25%).

**Comment by rnllv** [comment]
I plan to work on the following:

* For parse time reduction
1. Cache the html file contents on first read. Subsequent reads will be from memory. Tonal pages are read multiple times from disk currently.
2. As an extension of the first item, we can create this cache before hand in a multi threaded way.

* For json reduction
3. We can implement a trim mechanism that will consider only a subset of the regions or countries (as discussed over Slack)
4. Investigate if react-admin supports array based dataProviders (array of arrays) instead of object based ones (array of objects)
5. Rename attributes with short names.

**Comment by rnllv** [comment]
1. We've a decent amount of CACHE HIT for mock data. This should be high for real data. 
![image](https://user-images.githubusercontent.com/77854924/233841874-360f9500-d841-45a3-a951-d5f4c1ef8385.png)
Note: We're not shipping the CACHE HIT/MISS diagnostic as part of #192

**Comment by IanMayo** [comment]
Ok @rnllv - thanks

Note: IMHO we may be justified in the cost  of coding to improve performance, since at the end of the `parse` phase of the project, the `parse` routine only need to be run once - then we throw the code away.  So, low-tech solutions are preferred :-)

**Comment by IanMayo** [comment]
Aah, I´ve now seen how simple the cacheing it - that´s not too much of a burden :-)

**Comment by IanMayo** [comment]
Drop. Doesn't relate to current approach.
