### ISSUE TITLE
Process Regions

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#263]
Create a DITA imagemap to match the one in `PD_1.html`.  It should use the same image, and the same coordinates.

The source image map will always be in  `.\PlatformData\PD_1.html` under the data folder specified in the attributes.  The generated file will be in `target\dita\regions\regions.dita`.   

The DITA code will match that provided [here](https://github.com/DeepBlueCLtd/Fi3ldMan/blob/main/dita/regions/regions.dita)

The background image of the world will be copied to `target/dita/regions/content/images/world-map.gif`

The region/country name will come from the `Alt` attribute, and the target hrefs will be constructed as `./regions/regions.dita` (that's the current file, since we haven't generated the target files yet).  The actual target files will created in a future step (#264).

**Comment by ebenezer-melkamu** [comment]
@IanMayo is this the correct order of the tasks, and should all of this happen in the `parser` script? 

1. Copy the background image of the world to `regions/content/images/world-map.gif`.
2. Create a DITA image map that matches the one in `PD_1.html`, using the same image and coordinates.
3. Use the `Alt` attribute to provide the `region/country` name in the image map.
4. Construct the target `hrefs` as `./region/region.dita`, but be aware that if the publish process fails due to missing files linked from the imagemap, the `hrefs` may need to be commented out and replaced with `./regions.dita` target URLs. Note that the actual target files will be created in a future step (#264).

**Comment by IanMayo** [comment]
yes, that's right.

**Comment by ebenezer-melkamu** [comment]
@IanMayo so the subtasks of the second task would be something like this correct?
 1. Read the `PD_1.html` file by using a parser library
 2. parse the content of the html file
 3. Generate a `regions.dita` file and save it in `target\dita\regions\regions.dita`

**Comment by IanMayo** [comment]
For 2, you just need to parse the element with the name `image-map`, plus the `<img>` with `usemap` of `#image-map`
