### ISSUE TITLE
Handle DITA anchor mangling

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#426]
When the DITA-OT converts DITA to XML, it mangles the anchor ids.

This is our original HTML in `Phase_F.html`:
```
<a name="number2">
```

It is linked to using `<a href="#number2">Residue</a>`

This is what we have in DITA:
```
<p id="number2"/>
```

This is what is in the generated HTML:
```
<p class="p" id="Phase_F.html__number2"></p>
```

So, we need to similarly mangle the anchor ids as we process `htmlToDita`

Aah, hold on. `Phase_F.html` is the `id` of the `reference` element for the document. This would be a little more manageable if we stripped the file-suffix when we generate the `reference.id`

Let's switch to stripping the file suffix when specifying the `reference.id`.

Also when we are processing `htmlToDITA` we should modify relative anchor targets (include '#') to prepend the document id before the relative target and to include the filename id.  So: 
* `<a href="#number2">`  => `<a href="#Phase_f/number2">`
* `<a href="Phase_g.dita#number2">`  => `<a href="Phase_g.dita#Phase_g/number2">`

See the spec for `href` attributes here: https://docs.oasis-open.org/dita/v1.2/os/spec/common/thehrefattribute.html

**Comment by robintw** [comment]
Fixed in 13ffeb9, but interestingly DITA-OT doesn't seem to process links like `<a href="#Phase_f/number2">` and convert them properly when converting to HTML. It seems like I have to put the mangled HTML version in the DITA instead - in this case `#Phase_f__number2`. Is that ok, or is that likely to cause problems with other things?

Weirdly this seems different to what is shown in the spec document you linked to, but it definitely doesn't work if I just put `#Phase_f/number2` in the dita - it stays like that in the HTML, whereas the actual div it is linking to gets mangled to `Phase_f__number2`. Possibly a problem with DITA-OT?
