### ISSUE TITLE
Tiered logging

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#436]
I could do with viewing both warnings and info messages.

Could their be a hierarchy of logging?

* warnings - just see warnings (so the console will be empty if nothing has gone wrong)
* info - see warnings and info messages
* debug - see all

But, could we switch the "Processing generic file" messages from info to debug please?  So, `info` just has overview/summary information.

I don't want us to write a new logging lib - so this is just a "nice to have" if it's easy enough to implement.

**Comment by robintw** [comment]
This is fixed in #440. The logging is already tiered, so that info will show all info and warning messages, warnings will show just warnings etc - I suspect it was just hard to tell this because of the volume of information that was shown. I've switched the "Processing generic file" messages from info to debug, and that should help a lot.
