### ISSUE TITLE
DITA publish warnings

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#443]
* [x] Attribute value "100_unit_charlie" of type ID must be a NCName when namespaces are enabled (presume it's the leading digit) (mocked up in `100_unit_charlie.html`
* [x] ..../image020.jog does not exist
* [x] Element type "span" must be declared
* [x] The content of element type "p" must match (DITA structure)
* [x] Images/Dungons&Dragons does not exist or cannot be loaded.  Reproduced in `phase_g.html` (the ampersand gets fixed in the target image, but not in the `IMG` URL.
* [x] attribute "style" must be declared for element type "p" (fixed in code - by introducing new color shade and tidying source implementation in file A18
* [x] The resource referenced as file://xxx/yyy/Content/Images/demo_20Hz.jpg is capitalized differently on disk, using file://xxx/yyy/Content/Images/demo_20Jz.JPG (I think we need to convert file suffixes to lower case on "copy" and on "sanitise".
* [ ]  Enclosing div for anchor <a name="number1"></a> has no top value in file /Users/ianmayo/git/LegacyMan/data/Britain_Cmplx/anchor_trans_fit.html. Pattern re-produced in mock data. I _guess_ python is mistaking the valid top value of zero for a None.

**Comment by robintw** [comment]
These are all fixed in #445, except for the final one.

You're correct that the top value of zero is being mistaken for None in Python, but that's deliberate as there are a lot of divs with top values of zero, and we generally want to ignore them (if we don't ignore them we also run into issues with there being _multiple_ divs with a top value of zero, and our current logic for dealing with duplicate top values, which occur quite a lot, misbehaves in this situation). As I think there was only one page in the real input data that had this issue, I would suggest that the best way forward is to just edit that input file and change the value from `0` to `1`. I don't think it's worth the development time it would take to be able to filter out all of the other stuff another way.

What do you think?

**Comment by IanMayo** [comment]
Hello Robin,
> 0 to 1

Sure, that's fine. Will do, and will report back to you.  Testing for changing `top` covered in issue #442
