### ISSUE TITLE
Start walk from contents page

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/LegacyMan#508]
I think we currently walk the structure from the `PD_1.html` file.  While this is the most important file, the _actual_ root is a `Introduction/ContentsPage.html`.

I think we should switch to walking from that file - as a generic file.  It does include `PD_1.html`, and when our processing meets that file, it can start doing `special processing of regions file`.

So, I guess the command-line will start with `data` as source location - but we start walking from a different root file.

**Comment by robintw** [comment]
I've changed the code to process from the ContentsPage first, ignoring the PD_1 file so that we can process that separately. However, the ContentsPage itself isn't being parsed properly. That's because the main content of the page is in a div with ID `Layer2`, and we ignore all divs that start with `Layer`.

Can you check if this is the case in the real data? If so, we need to decide whether to fix it in the real data or try and change our code (which may be tricky, as we rely on excluding these divs when processing other files).

**Comment by IanMayo** [comment]
Yes, I'm sure it's in a layer like that. But, yesterday I fixed two other files that experienced the same problem. Once I've done that, I'll update the mock content. Hmm, maybe you can see the commit for the new pattern I introduced, and apply it to this page.

**Comment by IanMayo** [comment]
aah, @robintw - I see I've already done what I planned to do:
https://github.com/DeepBlueCLtd/LegacyMan/pull/504/files#diff-1d68ca24778b58d0113171d579284a1b04ae4237a15063550bf7aa269c26d0e5

ContentsPage no longer sits in a `Layer2`

**Comment by robintw** [comment]
ah yes, I've pulled from `develop` and that's fine.

The next problem I've run into is that when we process the `PD_1.html` file directly in `process_regions` we are outputting it to `regions.dita` in the root output directory. Is there a particular reason for this, and is it hang-over from starting at the regions file?

The ContentsPage links to the PD_1.html page - so it expects to find a PD_1.dita file in the same place in the tree after conversion.

Should we change our code to output the conversion of the PD_1.html file to a PD_1.dita file?

**Comment by IanMayo** [comment]
Oops: https://github.com/DeepBlueCLtd/LegacyMan/issues/510

Yes - let's do as you described.

**Comment by robintw** [comment]
Great. I think I've done it - it involves various changes to the mock data, can you check they all look sensible?

**Comment by robintw** [comment]
Fixed in #511
